# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!



target 'stockMarketSearch' do	

  pod 'Alamofire'
  pod 'AlamofireSwiftyJSON'
  pod 'SwiftSpinner'
  pod 'Alamofire-Synchronous', :git => 'https://github.com/Dalodd/Alamofire-Synchronous.git'
  pod 'SearchTextField'
  pod 'SwiftyJSON'
end

